name: code-analisis
on: push
env:
  DOCKER_PROJECT_NAME: data_structures_playground

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to docker registry
        run: docker login --username ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build docker image for project
        run: docker build --tag "${{ secrets.DOCKER_REGISTRY_USERNAME }}/$DOCKER_PROJECT_NAME:$GITHUB_REF_NAME-$GITHUB_RUN_ID" .

      - name: Push image to dockerhub
        run: docker push "${{ secrets.DOCKER_REGISTRY_USERNAME }}/$DOCKER_PROJECT_NAME:$GITHUB_REF_NAME-$GITHUB_RUN_ID"

  run_tests:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    steps:
      - name: Run RSpec
        run: docker run --pull always --rm "${{ secrets.DOCKER_REGISTRY_USERNAME }}/$DOCKER_PROJECT_NAME:$GITHUB_REF_NAME-$GITHUB_RUN_ID" bundle exec rspec

  run_static_code_analyser:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    steps:
      - name: Run rubocop (static code analyser)
        run: docker run --pull always --rm "${{ secrets.DOCKER_REGISTRY_USERNAME }}/$DOCKER_PROJECT_NAME:$GITHUB_REF_NAME-$GITHUB_RUN_ID" bundle exec rubocop

  run_vulnerabilities_checker:
    runs-on: ubuntu-latest
    needs: build_and_push_docker_image
    steps:
      - name: Run bundle-audit (vulnerability checker)
        run: docker run --pull always --rm "${{ secrets.DOCKER_REGISTRY_USERNAME }}/$DOCKER_PROJECT_NAME:$GITHUB_REF_NAME-$GITHUB_RUN_ID" bundle exec bundle-audit
